name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        
      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Installation des dépendances
        run: npm install
        
      - name: Construction de l'app web
        run: npm run build
        
      - name: Synchronisation Capacitor
        run: npx cap sync android
        
      - name: Configuration de Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
          
      - name: Compilation de l'APK
        run: |
          cd android
          gradle assembleDebug
          
      - name: Sauvegarde de l'APK
        uses: actions/upload-artifact@v4
        with:
          name: liste de présence 
          path: android/app/build/outputs/apk/debug/app-debug.apk
